production:
  key: "key"
  keys: 123456789
  hostname: 'production.example.com'
  array_key:
    - first_new
    - second_new
    - third_new
  other:
    values:
      - first_old
      - second_old
      - third_old
  values: 'James Bond'
  value: ''
